In [1]:
# se utiliza para el manejo de rutas y directorios.
import os

# Calculo cientifico y vectorial para python
import numpy as np

# Librerias para graficar
from matplotlib import pyplot

# Modulo de optimización de scipy
from scipy import optimize

# le dice a matplotlib que incruste gráficos en el cuaderno
%matplotlib inline

In [2]:
# Importar libreria para dividir entrenamiento y prueba
from sklearn.model_selection import train_test_split

In [3]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from datetime import datetime

In [4]:
#Acceder al drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
#Cargar datased
data = pd.read_csv('/content/drive/MyDrive/IA/Airlines.csv', header=0)

In [6]:
print(data)

            id Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  \
0            1      CO     269         SFO       IAH          3    15     205   
1            2      US    1558         PHX       CLT          3    15     222   
2            3      AA    2400         LAX       DFW          3    20     165   
3            4      AA    2466         SFO       DFW          3    20     195   
4            5      AS     108         ANC       SEA          3    30     202   
...        ...     ...     ...         ...       ...        ...   ...     ...   
539378  539379      CO     178         OGG       SNA          5  1439     326   
539379  539380      FL     398         SEA       ATL          5  1439     305   
539380  539381      FL     609         SFO       MKE          5  1439     255   
539381  539382      UA      78         HNL       SFO          5  1439     313   
539382  539383      US    1442         LAX       PHL          5  1439     301   

        Delay  
0          

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 539383 entries, 0 to 539382
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype 
---  ------       --------------   ----- 
 0   id           539383 non-null  int64 
 1   Airline      539383 non-null  object
 2   Flight       539383 non-null  int64 
 3   AirportFrom  539383 non-null  object
 4   AirportTo    539383 non-null  object
 5   DayOfWeek    539383 non-null  int64 
 6   Time         539383 non-null  int64 
 7   Length       539383 non-null  int64 
 8   Delay        539383 non-null  int64 
dtypes: int64(6), object(3)
memory usage: 37.0+ MB


In [8]:
columnas_categoricas = data.select_dtypes(include=['object']).columns

In [9]:
#Procesamiento de frases o palabras
for columna in columnas_categoricas:
  le = LabelEncoder()
  data[columna] = le.fit_transform(data[columna])

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 539383 entries, 0 to 539382
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   id           539383 non-null  int64
 1   Airline      539383 non-null  int64
 2   Flight       539383 non-null  int64
 3   AirportFrom  539383 non-null  int64
 4   AirportTo    539383 non-null  int64
 5   DayOfWeek    539383 non-null  int64
 6   Time         539383 non-null  int64
 7   Length       539383 non-null  int64
 8   Delay        539383 non-null  int64
dtypes: int64(9)
memory usage: 37.0 MB


In [11]:
print(data)

            id  Airline  Flight  AirportFrom  AirportTo  DayOfWeek  Time  \
0            1        4     269          253        135          3    15   
1            2       14    1558          217         60          3    15   
2            3        1    2400          154         80          3    20   
3            4        1    2466          253         80          3    20   
4            5        2     108           14        252          3    30   
...        ...      ...     ...          ...        ...        ...   ...   
539378  539379        4     178          203        264          5  1439   
539379  539380        8     398          252         16          5  1439   
539380  539381        8     609          253        184          5  1439   
539381  539382       13      78          128        253          5  1439   
539382  539383       14    1442          154        216          5  1439   

        Length  Delay  
0          205      1  
1          222      1  
2          165 

In [12]:
print(data.columns)

Index(['id', 'Airline', 'Flight', 'AirportFrom', 'AirportTo', 'DayOfWeek',
       'Time', 'Length', 'Delay'],
      dtype='object')


In [13]:
#eliminar columna id
columna_eliminada = 'id'
data.drop(columna_eliminada, axis=1, inplace=True)

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 539383 entries, 0 to 539382
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Airline      539383 non-null  int64
 1   Flight       539383 non-null  int64
 2   AirportFrom  539383 non-null  int64
 3   AirportTo    539383 non-null  int64
 4   DayOfWeek    539383 non-null  int64
 5   Time         539383 non-null  int64
 6   Length       539383 non-null  int64
 7   Delay        539383 non-null  int64
dtypes: int64(8)
memory usage: 32.9 MB


In [15]:
# Division de dataset en entrenamiento y prueba
train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)

In [16]:
print(train_data)

        Airline  Flight  AirportFrom  AirportTo  DayOfWeek  Time  Length  \
498081        7     796          214         79          3   900     143   
203828       15    3586          243        258          7  1185      80   
156549        1     705          159         80          5   365     250   
66053         5    2825           35        197          6  1090     207   
165376        8    1102           61        241          5   818     150   
...         ...     ...          ...        ...        ...   ...     ...   
110268       14      20          217        128          2   715     403   
259178       12    6401          224        253          4   375     125   
365838       11    6594           27        159          3   360     160   
131932       13     938           79        208          3   955     144   
121958        5    2952          277        159          3   420     159   

        Delay  
498081      0  
203828      1  
156549      1  
66053       0  
165376 

In [17]:
print(test_data)

        Airline  Flight  AirportFrom  AirportTo  DayOfWeek  Time  Length  \
442150       12    6477          262        154          7   881      85   
229730       13     310           79        159          2   665     223   
69994        15    1739          202        153          7   465      85   
414293        3    1085          148         60          5   990     131   
171704        2     129          252         98          5  1150     235   
...         ...     ...          ...        ...        ...   ...     ...   
290929        6    5579          121         16          5  1064      66   
466596       12    6358          246        154          1  1186      44   
392244       12    4794           65        261          4   750     102   
502274        8     277           35         16          3  1118     172   
381831        3     271          153         44          3  1177      63   

        Delay  
442150      1  
229730      1  
69994       1  
414293      0  
171704 

In [18]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 431506 entries, 498081 to 121958
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Airline      431506 non-null  int64
 1   Flight       431506 non-null  int64
 2   AirportFrom  431506 non-null  int64
 3   AirportTo    431506 non-null  int64
 4   DayOfWeek    431506 non-null  int64
 5   Time         431506 non-null  int64
 6   Length       431506 non-null  int64
 7   Delay        431506 non-null  int64
dtypes: int64(8)
memory usage: 29.6 MB


In [19]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 107877 entries, 442150 to 381831
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Airline      107877 non-null  int64
 1   Flight       107877 non-null  int64
 2   AirportFrom  107877 non-null  int64
 3   AirportTo    107877 non-null  int64
 4   DayOfWeek    107877 non-null  int64
 5   Time         107877 non-null  int64
 6   Length       107877 non-null  int64
 7   Delay        107877 non-null  int64
dtypes: int64(8)
memory usage: 7.4 MB


In [20]:
train_data.to_csv("train.csv", index=False)

In [21]:
test_data.to_csv("test.csv", index=False)

In [22]:
#Carga de dataset de entrenamiento
data = pd.read_csv('/content/train.csv')

In [23]:
X = data.iloc[:, :7]
y = data.iloc[:, 7]
m = y.size

In [24]:
print(X)
print('*'*25)
print(y)

        Airline  Flight  AirportFrom  AirportTo  DayOfWeek  Time  Length
0             7     796          214         79          3   900     143
1            15    3586          243        258          7  1185      80
2             1     705          159         80          5   365     250
3             5    2825           35        197          6  1090     207
4             8    1102           61        241          5   818     150
...         ...     ...          ...        ...        ...   ...     ...
431501       14      20          217        128          2   715     403
431502       12    6401          224        253          4   375     125
431503       11    6594           27        159          3   360     160
431504       13     938           79        208          3   955     144
431505        5    2952          277        159          3   420     159

[431506 rows x 7 columns]
*************************
0         0
1         1
2         1
3         0
4         1
         ..

In [25]:
def  featureNormalize(X):
    X_norm = X.copy()
    mu = np.zeros(X.shape[1])
    sigma = np.zeros(X.shape[1])

    mu = np.mean(X, axis = 0)
    sigma = np.std(X, axis = 0)
    X_norm = (X - mu) / sigma

    return X_norm, mu, sigma

In [26]:
# llama featureNormalize con los datos cargados
X_norm, mu, sigma = featureNormalize(X)

print(X)
print('Media calculada:', mu)
print('Desviación estandar calculada:', sigma)
print(X_norm)

        Airline  Flight  AirportFrom  AirportTo  DayOfWeek  Time  Length
0             7     796          214         79          3   900     143
1            15    3586          243        258          7  1185      80
2             1     705          159         80          5   365     250
3             5    2825           35        197          6  1090     207
4             8    1102           61        241          5   818     150
...         ...     ...          ...        ...        ...   ...     ...
431501       14      20          217        128          2   715     403
431502       12    6401          224        253          4   375     125
431503       11    6594           27        159          3   360     160
431504       13     938           79        208          3   955     144
431505        5    2952          277        159          3   420     159

[431506 rows x 7 columns]
Media calculada: Airline           9.333615
Flight         2426.334969
AirportFrom     144.105092

In [27]:
def sigmoid(z):
    # Calcula la sigmoide de una entrada z
    # convierte la intrada a un arreglo numpy
    z = np.array(z)

    g = np.zeros(z.shape)

    g = 1 / (1 + np.exp(-z))

    return g

In [28]:
# Prueba la implementacion de la funcion sigmoid
z = 0
g = sigmoid(z)

print('g(', z, ') = ', g)

g( 0 ) =  0.5


In [29]:
# Configurar la matriz adecuadamente, y agregar una columna de unos que corresponde al termino de intercepción.
m, n = X.shape
# Agraga el termino de intercepción a A
X = np.concatenate([np.ones((m, 1)), X], axis=1)

In [30]:
print(X)

[[1.000e+00 7.000e+00 7.960e+02 ... 3.000e+00 9.000e+02 1.430e+02]
 [1.000e+00 1.500e+01 3.586e+03 ... 7.000e+00 1.185e+03 8.000e+01]
 [1.000e+00 1.000e+00 7.050e+02 ... 5.000e+00 3.650e+02 2.500e+02]
 ...
 [1.000e+00 1.100e+01 6.594e+03 ... 3.000e+00 3.600e+02 1.600e+02]
 [1.000e+00 1.300e+01 9.380e+02 ... 3.000e+00 9.550e+02 1.440e+02]
 [1.000e+00 5.000e+00 2.952e+03 ... 3.000e+00 4.200e+02 1.590e+02]]


In [31]:
def calcularCosto(theta, X, y):
    # Inicializar algunos valores utiles
    m = y.size  # numero de ejemplos de entrenamiento
    #epsilon = 1e-8

    J = 0
    h = sigmoid(X.dot(theta.T))
    J = (1 / m) * np.sum(-y.dot(np.log(h)) - (1 - y).dot(np.log(1 - h)))

    return J

In [32]:
def descensoGradiente(theta, X, y, alpha, num_iters):
    # Inicializa algunos valores
    m = y.shape[0] # numero de ejemplos de entrenamiento

    # realiza una copia de theta, el cual será acutalizada por el descenso por el gradiente
    theta = theta.copy()
    J_history = []

    for i in range(num_iters):
        h = sigmoid(X.dot(theta.T))
        theta = theta - (alpha / m) * (h - y).dot(X)

        J_history.append(calcularCosto(theta, X, y))
    return theta, J_history

In [33]:
#Carga de dataset de prueba
data = pd.read_csv('/content/test.csv')
print(data)

        Airline  Flight  AirportFrom  AirportTo  DayOfWeek  Time  Length  \
0            12    6477          262        154          7   881      85   
1            13     310           79        159          2   665     223   
2            15    1739          202        153          7   465      85   
3             3    1085          148         60          5   990     131   
4             2     129          252         98          5  1150     235   
...         ...     ...          ...        ...        ...   ...     ...   
107872        6    5579          121         16          5  1064      66   
107873       12    6358          246        154          1  1186      44   
107874       12    4794           65        261          4   750     102   
107875        8     277           35         16          3  1118     172   
107876        3     271          153         44          3  1177      63   

        Delay  
0           1  
1           1  
2           1  
3           0  
4      

In [34]:
#extrayendo filas del Dataset de pruebas para comprobar
fila_deseada = 1;
if fila_deseada < len(data) :
  fila_completa = data.iloc[fila_deseada].to_numpy()
  print(fila_completa)
else:
  print("la fila no existe")

[ 13 310  79 159   2 665 223   1]


In [47]:
fila_deseada = 3;
if fila_deseada < len(data) :
  fila_completa = data.iloc[fila_deseada].to_numpy()
  print(fila_completa)
else:
  print("la fila no existe")

[   3 1085  148   60    5  990  131    0]


In [62]:
# Elegir algun valor para alpha (probar varias alternativas)
alpha = 0.001
num_iters = 2000

# inicializa theta y ejecuta el descenso por el gradiente
theta = np.zeros(8)
theta, J_history = descensoGradiente(theta, X, y, alpha, num_iters)

# Grafica la convergencia del costo
#pyplot.plot(np.arange(len(J_history)), J_history, lw=2)
#pyplot.xlabel('Numero de iteraciones')
#pyplot.ylabel('Costo J')

# Muestra los resultados del descenso por el gradiente
print('theta calculado por el descenso por el gradiente: {:s}'.format(str(theta)))

# verificar si existe retraso en el vuelo o no
X_array = [1, 13, 310, 79, 159, 2, 665, 223]
#X_array = [1, 3, 1085, 148, 60, 5, 990, 131]
aprueba = sigmoid(np.dot(X_array, theta))   # Se debe cambiar esto

print('El resultado entre falso y verdadero es (usando el descenso por el gradiente):{:.0f}'.format(aprueba))

<ipython-input-27-22f640bc02db>:8: RuntimeWarning: overflow encountered in exp
  g = 1 / (1 + np.exp(-z))
<ipython-input-31-80d181a16dea>:8: RuntimeWarning: divide by zero encountered in log
  J = (1 / m) * np.sum(-y.dot(np.log(h)) - (1 - y).dot(np.log(1 - h)))


theta calculado por el descenso por el gradiente: [-0.02599827  0.127475    0.62680583 -0.42079431  0.02168192 -0.15151361
  0.6025848  -0.42994597]
El resultado entre falso y verdadero es (usando el descenso por el gradiente):1


In [ ]:
##################Utilizando optimize.minimize ##################

In [54]:
def costFunction(theta, X, y):
    # Inicializar algunos valores utiles
    m = y.size  # numero de ejemplos de entrenamiento
    epsilon = 1e-8

    J = 0
    grad = np.zeros(theta.shape)

    h = sigmoid(X.dot(theta.T))

    J = (1 / m) * np.sum(-y.dot(np.log(h+epsilon)) - (1 - y).dot(np.log(1 - h+epsilon)))
    grad = (1 / m) * (h - y).dot(X)

    return J, grad

In [55]:
# Inicializacion de parametros de ajuste
initial_theta = np.zeros(n+1)
print(initial_theta)
cost, grad = costFunction(initial_theta, X, y)

print('Costo en theta inicial (zeros): {:.3f}'.format(cost))
print('Costo esperado (aproximado): 0.693\n')
print(grad)
print('Gradiente en theta inicial (zeros):')
print('\t[{:.4f}, {:.4f}, {:.4f}]'.format(*grad))
print('Gradiente esperado (aproximado):\n\t[-0.1000, -12.0092, -11.2628]\n')

[0. 0. 0. 0. 0. 0. 0. 0.]
Costo en theta inicial (zeros): 0.693
Costo esperado (aproximado): 0.693

[5.44302976e-02 3.29407934e-01 1.78975765e+02 7.10304144e+00
 5.92896275e+00 2.39223788e-01 2.30658589e+01 5.76797310e+00]
Gradiente en theta inicial (zeros):
	[0.0544, 0.3294, 178.9758]
Gradiente esperado (aproximado):
	[-0.1000, -12.0092, -11.2628]



In [56]:
# Establecer las opciones para optimize.minimize
options= {'maxiter': 1000}

# revisar la documentacion de scipy's optimize.minimize para mayor descripcion de los parametros
# La funcion devuekve un objeto `OptimizeResult`
# Se utiliza el algoritmo de Newton truncado para la optimización.
res = optimize.minimize(costFunction,
                        initial_theta,
                        (X, y),
                        jac=True,
                        method='TNC',
                        options=options)

# la propiedad fun del objeto devuelto por `OptimizeResult`
# contiene el valor del costFunction de un theta optimizado
cost = res.fun

# Theta optimizada esta en la propiedad x
theta = res.x

# Imprimir theta en la pantalla
print('Costo con un valor de theta encontrado por optimize.minimize: {:.3f}'.format(cost))
print('Costo esperado (aproximado): 0.203\n');

print('theta:')
print('\t[{:.3f}, {:.3f}, {:.3f}]'.format(*theta))
print('Theta esperado (aproximado):\n\t[-25.161, 0.206, 0.201]')

<ipython-input-56-0dfcfa2e2ef1>:7: OptimizeWarning: Unknown solver options: maxiter
  res = optimize.minimize(costFunction,


Costo con un valor de theta encontrado por optimize.minimize: 0.670
Costo esperado (aproximado): 0.203

theta:
	[-1.527, 0.029, -0.000]
Theta esperado (aproximado):
	[-25.161, 0.206, 0.201]


In [57]:
def plotDecisionBoundary(plotData, theta, X, y):

    # hacer que theta sera un arreglo numpy
    theta = np.array(theta)

    # Graficar los datos (recordar que la primera columna en X es la intercepción)
    plotData(X[:, 1:8], y)

    if X.shape[1] <= 8:
        # Solo se requieren 2 puntos para definir una linea, para lo cual se eligen dos puntos finales
        plot_x = np.array([np.min(X[:, 1]) - 2, np.max(X[:, 1]) + 2])

        # Calcular la línea límite de decisión
        plot_y = (-1. / theta[2]) * (theta[1] * plot_x + theta[0])

        print(plot_x)
        print(plot_y)
        # Graficar y ajustar los ejes para una mejor visualización
        pyplot.plot(plot_x, plot_y)

        # Leyenda, especifica para el ejercicio
        pyplot.legend(['Retraso', 'Sin Retraso', 'Limite de decisión'])
        pyplot.xlim([30, 100])
        pyplot.ylim([30, 100])
    else:
        # Rango de la grilla
        u = np.linspace(-1, 1.5, 50)
        v = np.linspace(-1, 1.5, 50)

        z = np.zeros((u.size, v.size))
        # Evalua z = theta*x sobre la grilla
        for i, ui in enumerate(u):
            for j, vj in enumerate(v):
                z[i, j] = np.dot(mapFeature(ui, vj), theta)

        z = z.T  # importante transponer z antes de llamar al contorno
        # print(z)

        # Plot z = 0
        pyplot.contour(u, v, z, levels=[0], linewidths=2, colors='g')
        pyplot.contourf(u, v, z, levels=[np.min(z), 0, np.max(z)], cmap='Greens', alpha=0.4)

In [58]:
def predict(theta, X):
    m = X.shape[0] # Numero de ejemplo de entrenamiento

    p = np.zeros(m)

    p = np.round(sigmoid(X.dot(theta.T)))
    return p

In [61]:
#  Predice la probabilidad de retraso de un vuelo
prob = sigmoid(np.dot([1, 13, 310, 79, 159, 2, 665, 223], theta))
print('El resultado entre falso y verdadero es: {:.3f}'.format(prob))
print('Valor esperado: 0.775 +/- 0.002\n')

# Compute accuracy on our training set
p = predict(theta, X)
print('Precisión de entrenamiento: {:.2f} %'.format(np.mean(p == y) * 100))
print('Precisión esperada (aproximadamente): 89.00 %')

El resultado entre falso y verdadero es: 0.493
Valor esperado: 0.775 +/- 0.002

Precisión de entrenamiento: 58.39 %
Precisión esperada (aproximadamente): 89.00 %
